### ISSUE TITLE
Phoenix LiveReload is not working

### ISSUE THREAD

**Issue by hafizio** [nanobox-quickstarts/nanobox-phoenix#2]
I was testing the development environment using nanobox by running `nanobox run`. I always get the error message saying:

```
Uh oh, the live filesystem watcher has panic'ed.
We'll go ahead and rollover to a slower polling solution.
```
I also noticed that the LiveReload feature in no longer working.

This is by `boxfile.yml`

```
run.config:
  engine: elixir

  dev_packages:
    - nodejs
    - inotify-tools

  cache_dirs:
    - ./assets/node_modules

  extra_path_dirs:
    - ./assets/node_modules/.bin

  fs_watch: true

deploy.config:
  extra_steps:
    - mix phx.digest

  before_live:
    web.main:
      - mix ecto.create --quiet
      - mix ecto.migrate

data.db:
  image: nanobox/postgresql:9.5

web.main:
  start: node-start mix phx.server
```
 
Is there any workaround for this issue?

Thanks!
